#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          automaster
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: configure the node to become a master
### END INIT INFO

cd /root/pi/
./become_pandemic_master

