#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          automaster
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: your description here
### END INIT INFO
cd /root/pi/
./become_pandemic_master > master.log 2>&1

